services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/django.dev.dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ..
      dockerfile: ./docker/node.dev.dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
