version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/django.dev.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend/drf_backend/static
      - media_volume:/backend/drf_backend/media
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ..
      dockerfile: ./docker/node.dev.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontend_build:/frontend/build
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/backend/drf_backend/static
      - media_volume:/backend/drf_backend/media
      - frontend_build:/frontend/build
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
  frontend_build:
